image: "node:8.10.0"

pipelines: 
  branches:
    staging: 
      - step:
          name: "Install devDependencies"
          script: 
          - "npm install"
          - "npm run build"
          - "npm run build:server"
          - "npm test"
